name: Build macOS

on:
  push:
    branches:
    - release/production

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Add OSX certificate
      env:
        CERTIFICATE_OSX_P12: ${{ secrets.CERTIFICATE_OSX_P12 }}
        CERTIFICATE_OSX_PASSWORD: ${{ secrets.CERTIFICATE_OSX_PASSWORD }}
      run: |
        chmod +x build/mac/cert.sh
        ./build/mac/cert.sh

    - name: install dependencies
      run: npm i

    - name: build all architectures
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        APPLE_TEAM_ID: 7459JWM5TY
      run: npm run build:mac -- --publish always