name: Build Windows

on:
  push:
    branches:
    - release/production

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: install dependencies
      run: npm i
      
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: npm run build:win -- --publish always

    # - name: Publish to Store
    #   uses: isaacrlevin/windows-store-action@1.0
    #   with:
    #     tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
    #     client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
    #     client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
    #     app-id: 9PL7PLM5BFT2
    #     package-path: "${{ github.workspace }}/dist/"